#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

export Q2_PROJECT="${Q2_PROJECT:-q2}"

export ORANGE_SOURCE_MONGO_HOST="${ORANGE_SOURCE_MONGO_HOST:-${ORANGE_MONGO_HOST:-127.0.0.1}}"
export ORANGE_SOURCE_MONGO_PORT="${ORANGE_SOURCE_MONGO_PORT:-${ORANGE_MONGO_PORT:-27018}}"
export ORANGE_SOURCE_MONGO_DB="${ORANGE_SOURCE_MONGO_DB:-public}"
export ORANGE_SOURCE_MONGO_AUTH_SOURCE="${ORANGE_SOURCE_MONGO_AUTH_SOURCE:-public}"
export ORANGE_SOURCE_MONGO_USER="${ORANGE_SOURCE_MONGO_USER:-orange}"
export ORANGE_SOURCE_MONGO_PASSWORD="${ORANGE_SOURCE_MONGO_PASSWORD:-${ORANGE_MONGO_PASSWORD:-orange_p@ss}}"

export ORANGE_STORE_MONGO_HOST="${ORANGE_STORE_MONGO_HOST:-${ORANGE_MONGO_HOST:-127.0.0.1}}"
export ORANGE_STORE_MONGO_PORT="${ORANGE_STORE_MONGO_PORT:-${ORANGE_MONGO_PORT:-27018}}"
export ORANGE_STORE_MONGO_DB="${ORANGE_STORE_MONGO_DB:-ai}"
export ORANGE_STORE_MONGO_AUTH_SOURCE="${ORANGE_STORE_MONGO_AUTH_SOURCE:-ai}"
export ORANGE_STORE_MONGO_USER="${ORANGE_STORE_MONGO_USER:-orange}"
export ORANGE_STORE_MONGO_PASSWORD="${ORANGE_STORE_MONGO_PASSWORD:-${ORANGE_MONGO_PASSWORD:-orange_p@ss}}"

if [ "$#" -gt 0 ]; then
  exec ./venv/bin/python llm/q2/q2_improver.py "$@"
fi

exec ./venv/bin/python llm/q2/q2_improver.py \
  --limit "${Q2_IMPROVER_LIMIT:-80}" \
  --hours "${Q2_IMPROVER_HOURS:-6}" \
  --codex-timeout "${Q2_IMPROVER_CODEX_TIMEOUT:-900}"
