#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

export Q2_PROJECT="${Q2_PROJECT:-q2}"
export Q2_SERVER="${Q2_SERVER:-http://127.0.0.1:3184}"
export Q2_LOCAL_TRAINER_MODE="${Q2_LOCAL_TRAINER_MODE:-step}"
export Q2_LOCAL_TRAINER_INTERVAL="${Q2_LOCAL_TRAINER_INTERVAL:-1}"
export Q2_LOCAL_TRAINER_BATCH="${Q2_LOCAL_TRAINER_BATCH:-1}"
export Q2_LOCAL_TRAINER_TIMEOUT="${Q2_LOCAL_TRAINER_TIMEOUT:-180}"
export Q2_LOCAL_TRAINER_RETRIES="${Q2_LOCAL_TRAINER_RETRIES:-3}"
export Q2_LOCAL_TRAIN_LIMIT="${Q2_LOCAL_TRAIN_LIMIT:-2000}"
export Q2_LOCAL_EVAL_TRAIN_LIMIT="${Q2_LOCAL_EVAL_TRAIN_LIMIT:-2000}"

export Q2_LOCAL_ENABLED="${Q2_LOCAL_ENABLED:-1}"
export Q2_OLLAMA_URL="${Q2_OLLAMA_URL:-http://127.0.0.1:11434}"
export Q2_OLLAMA_MODEL="${Q2_OLLAMA_MODEL:-qwen3-coder:30b}"
export Q2_OLLAMA_TIMEOUT="${Q2_OLLAMA_TIMEOUT:-180}"

export ORANGE_SOURCE_MONGO_HOST="${ORANGE_SOURCE_MONGO_HOST:-${ORANGE_MONGO_HOST:-127.0.0.1}}"
export ORANGE_SOURCE_MONGO_PORT="${ORANGE_SOURCE_MONGO_PORT:-${ORANGE_MONGO_PORT:-27018}}"
export ORANGE_SOURCE_MONGO_DB="${ORANGE_SOURCE_MONGO_DB:-public}"
export ORANGE_SOURCE_MONGO_AUTH_SOURCE="${ORANGE_SOURCE_MONGO_AUTH_SOURCE:-public}"
export ORANGE_SOURCE_MONGO_USER="${ORANGE_SOURCE_MONGO_USER:-orange}"
export ORANGE_SOURCE_MONGO_PASSWORD="${ORANGE_SOURCE_MONGO_PASSWORD:-${ORANGE_MONGO_PASSWORD:-orange_p@ss}}"

export ORANGE_STORE_MONGO_HOST="${ORANGE_STORE_MONGO_HOST:-${ORANGE_MONGO_HOST:-127.0.0.1}}"
export ORANGE_STORE_MONGO_PORT="${ORANGE_STORE_MONGO_PORT:-${ORANGE_MONGO_PORT:-27018}}"
export ORANGE_STORE_MONGO_DB="${ORANGE_STORE_MONGO_DB:-ai}"
export ORANGE_STORE_MONGO_AUTH_SOURCE="${ORANGE_STORE_MONGO_AUTH_SOURCE:-ai}"
export ORANGE_STORE_MONGO_USER="${ORANGE_STORE_MONGO_USER:-orange}"
export ORANGE_STORE_MONGO_PASSWORD="${ORANGE_STORE_MONGO_PASSWORD:-${ORANGE_MONGO_PASSWORD:-orange_p@ss}}"

exec ./venv/bin/python -m llm.q2.q2_local_lm_trainer "$@"
