#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

export Q2_PROJECT="${Q2_PROJECT:-q2}"
export Q2_WORKER_SERVER="${Q2_WORKER_SERVER:-http://127.0.0.1:3184}"
export Q2_WORKER_BATCH_SIZE="${Q2_WORKER_BATCH_SIZE:-120}"
export Q2_WORKER_PROFILE_INTERVAL="${Q2_WORKER_PROFILE_INTERVAL:-600}"
export Q2_WORKER_WARM_INTERVAL="${Q2_WORKER_WARM_INTERVAL:-30}"
export Q2_WORKER_RETEST_INTERVAL="${Q2_WORKER_RETEST_INTERVAL:-180}"
export Q2_WORKER_SAMPLE_LIMIT="${Q2_WORKER_SAMPLE_LIMIT:-1000}"
export Q2_WORKER_TIMEOUT="${Q2_WORKER_TIMEOUT:-180}"
export Q2_WORKER_CONCURRENCY="${Q2_WORKER_CONCURRENCY:-4}"
export Q2_WORKER_RETEST_CONCURRENCY="${Q2_WORKER_RETEST_CONCURRENCY:-3}"

export ORANGE_SOURCE_MONGO_HOST="${ORANGE_SOURCE_MONGO_HOST:-${ORANGE_MONGO_HOST:-127.0.0.1}}"
export ORANGE_SOURCE_MONGO_PORT="${ORANGE_SOURCE_MONGO_PORT:-${ORANGE_MONGO_PORT:-27018}}"
export ORANGE_SOURCE_MONGO_DB="${ORANGE_SOURCE_MONGO_DB:-public}"
export ORANGE_SOURCE_MONGO_AUTH_SOURCE="${ORANGE_SOURCE_MONGO_AUTH_SOURCE:-public}"
export ORANGE_SOURCE_MONGO_USER="${ORANGE_SOURCE_MONGO_USER:-orange}"
export ORANGE_SOURCE_MONGO_PASSWORD="${ORANGE_SOURCE_MONGO_PASSWORD:-${ORANGE_MONGO_PASSWORD:-orange_p@ss}}"

export ORANGE_STORE_MONGO_HOST="${ORANGE_STORE_MONGO_HOST:-${ORANGE_MONGO_HOST:-127.0.0.1}}"
export ORANGE_STORE_MONGO_PORT="${ORANGE_STORE_MONGO_PORT:-${ORANGE_MONGO_PORT:-27018}}"
export ORANGE_STORE_MONGO_DB="${ORANGE_STORE_MONGO_DB:-ai}"
export ORANGE_STORE_MONGO_AUTH_SOURCE="${ORANGE_STORE_MONGO_AUTH_SOURCE:-ai}"
export ORANGE_STORE_MONGO_USER="${ORANGE_STORE_MONGO_USER:-orange}"
export ORANGE_STORE_MONGO_PASSWORD="${ORANGE_STORE_MONGO_PASSWORD:-${ORANGE_MONGO_PASSWORD:-orange_p@ss}}"

exec ./venv/bin/python llm/q2/q2_macbook_worker.py "$@"
